#!/usr/bin/env php
<?php

use Illuminate\Console\Application;
use Illuminate\Events\Dispatcher;
use Ypho\Console\Container;

require __DIR__.'/vendor/autoload.php';

$container = new Container();
$events = new Dispatcher($container);
$artisan = new Application($container, $events, 'v1');

$artisan->setName('Heartbreak Console');

// General commands
$artisan->resolve(\Ypho\Console\Commands\Heartbeat::class);

$artisan->run();